apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: QA
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA2
          artifact-id: 6ade8eca-3e70-4051-9c4c-c3f2a650c796
          target-environment: QA-env

