apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: QA
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA2
          artifact-id: b7b3fe7e-08c7-4c61-af69-0bf698617a2b
          target-environment: QA-env

